### ISSUE TITLE
Crashed on Magma Server 

### ISSUE THREAD

**Issue by DartPower** [Napoleon-ZoomberParts/Minecraft-Sex-Mod-Jenny-1.12.2-Forge#18]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore_v1.10.61_mc1.12.2.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  CorePlugin (SmoothFont-mc1.12.2-2.1.2.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-55.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
  PatcherPlugin (GraviSuite-Patcher-1.0.0.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 31.07.21 16:00
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Sex Mod (sexmod)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/entity/Render
	at com.schnurritv.sexmod.util.Handlers.RegistryHandler.preInitRegistries(RegistryHandler.java:21)
	at com.schnurritv.sexmod.Main.preInit(Main.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:600)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:103)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:337)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:169)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:688)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.entity.Render
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:223)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 37 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Magma Version: d16a406-DEV
	Operating System: Linux (amd64) version 4.19.0-17-amd64
	Java Version: 1.8.0_292, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 5335117808 bytes (5087 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 20 total; -Xms8192m -Xmx8192m -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 109 mods loaded, 109 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version                  | Source                                             | Signature                                |
	|:----- |:--------------------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                         | 1.12.2                   | minecraft.jar                                      | None                                     |
	| LCH   | mcp                               | 9.42                     | minecraft.jar                                      | None                                     |
	| LCH   | FML                               | 8.0.99.99                | Magma-d16a406-DEV-server.jar                       | None                                     |
	| LCH   | forge                             | 14.23.5.2855             | Magma-d16a406-DEV-server.jar                       | None                                     |
	| LCH   | creativecoredummy                 | 1.0.0                    | minecraft.jar                                      | None                                     |
	| LCH   | gravisuitepatchcore               | 1.0                      | minecraft.jar                                      | None                                     |
	| LCH   | smoothfontcore                    | mc1.12.2-2.1.2           | minecraft.jar                                      | None                                     |
	| LCH   | opencomputers|core                | 1.7.5.192                | minecraft.jar                                      | None                                     |
	| LCH   | techguns_core                     | 1.12.2-1.0               | minecraft.jar                                      | None                                     |
	| LCH   | securitycraft                     | v1.8.23.1                | [1.12.2] SecurityCraft v1.8.23.1.jar               | None                                     |
	| LCH   | bspkrscore                        | 7.6.0.1                  | [1.12]bspkrsCore-universal-7.6.0.1.jar             | None                                     |
	| LCH   | armorstatushud                    | 1.43.0                   | [1.12]ArmorStatusHUD-client-1.43.0.jar             | None                                     |
	| LCH   | ic2                               | 2.8.170-ex112            | industrialcraft-2-2.8.170-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCH   | advanced_solar_panels             | 4.3.0                    | Advanced+Solar+Panels-4.3.0.jar                    | None                                     |
	| LCH   | aiimprovements                    | 0.0.1.3                  | AIImprovements-1.12-0.0.1b3.jar                    | None                                     |
	| LCH   | crafttweaker                      | 4.1.20                   | CraftTweaker2-1.12-4.1.20.655.jar                  | None                                     |
	| LCH   | mtlib                             | 3.0.6                    | MTLib-3.0.6.jar                                    | None                                     |
	| LCH   | modtweaker                        | 4.0.18                   | modtweaker-4.0.18.jar                              | None                                     |
	| LCH   | jei                               | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                          | None                                     |
	| LCH   | appleskin                         | 1.0.14                   | AppleSkin-mc1.12-1.0.14.jar                        | None                                     |
	| LCH   | appliedenergistics2               | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCH   | base                              | 3.13.0                   | base-1.12.2-3.13.0.jar                             | None                                     |
	| LCH   | betterhud                         | 1.4.4                    | betterhud-1.12.2-1.4.4.jar                         | None                                     |
	| LCH   | buildcraftlib                     | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCH   | buildcraftcore                    | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCH   | buildcraftenergy                  | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCH   | forestry                          | 5.8.2.387                | forestry_1.12.2-5.8.2.387.jar                      | None                                     |
	| LCH   | binniecore                        | 2.5.1.203                | binnie-mods-1.12.2-2.5.1.203.jar                   | None                                     |
	| LCH   | binniedesign                      | 2.5.1.203                | binnie-mods-1.12.2-2.5.1.203.jar                   | None                                     |
	| LCH   | genetics                          | 2.5.1.203                | binnie-mods-1.12.2-2.5.1.203.jar                   | None                                     |
	| LCH   | botany                            | 2.5.1.203                | binnie-mods-1.12.2-2.5.1.203.jar                   | None                                     |
	| LCH   | extrabees                         | 2.5.1.203                | binnie-mods-1.12.2-2.5.1.203.jar                   | None                                     |
	| LCH   | extratrees                        | 2.5.1.203                | binnie-mods-1.12.2-2.5.1.203.jar                   | None                                     |
	| LCH   | buildcraftbuilders                | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCH   | buildcrafttransport               | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCH   | buildcraftsilicon                 | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCH   | buildcraftcompat                  | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCH   | buildcraftfactory                 | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCH   | buildcraftrobotics                | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCH   | chisel                            | MC1.12.2-1.0.2.45        | Chisel-MC1.12.2-1.0.2.45.jar                       | None                                     |
	| LCH   | chiselsandbits                    | 14.33                    | chiselsandbits-14.33.jar                           | None                                     |
	| LCH   | clumps                            | 3.1.2                    | Clumps-3.1.2.jar                                   | None                                     |
	| LCH   | codechickenlib                    | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | redstoneflux                      | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
	| LCH   | cofhcore                          | 4.6.6                    | CoFHCore-1.12.2-4.6.6.1-universal.jar              | None                                     |
	| LCH   | cofhworld                         | 1.4.0                    | CoFHWorld-1.12.2-1.4.0.1-universal.jar             | None                                     |
	| LCH   | corpse                            | 1.12.2-1.0.8             | corpse-1.12.2-1.0.8.jar                            | None                                     |
	| LCH   | coronavirus_infection_mod         | 2.5.0                    | covid-19-infection-mod-v-2-5-0.jar                 | None                                     |
	| LCH   | craftstudioapi                    | 1.0.0                    | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
	| LCH   | crafttweakerjei                   | 2.0.3                    | CraftTweaker2-1.12-4.1.20.655.jar                  | None                                     |
	| LCH   | creativecore                      | 1.10.0                   | CreativeCore_v1.10.61_mc1.12.2.jar                 | None                                     |
	| LCH   | creativeplus                      | 1.0.2                    | CreativePlus+MC1.12.2+v1.0.2.jar                   | None                                     |
	| LCH   | eguilib                           | 0.1.2                    | eguilib-0.1.2.jar                                  | None                                     |
	| LCH   | endercore                         | 1.12.2-0.5.76            | EnderCore-1.12.2-0.5.76.jar                        | None                                     |
	| LCH   | thermalfoundation                 | 2.6.7                    | ThermalFoundation-1.12.2-2.6.7.1-universal.jar     | None                                     |
	| LCH   | thermalexpansion                  | 5.5.7                    | ThermalExpansion-1.12.2-5.5.7.1-universal.jar      | None                                     |
	| LCH   | enderio                           | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCH   | enderiointegrationtic             | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCH   | enderiobase                       | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCH   | enderioconduits                   | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCH   | enderioconduitsappliedenergistics | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCH   | opencomputers                     | 1.7.5.192                | OpenComputers-MC1.12.2-1.7.5.192.jar               | None                                     |
	| LCH   | enderioconduitsopencomputers      | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCH   | enderioconduitsrefinedstorage     | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCH   | enderiointegrationforestry        | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCH   | enderiointegrationticlate         | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCH   | enderioinvpanel                   | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCH   | enderiomachines                   | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCH   | enderiopowertools                 | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCH   | externaltweaker                   | 0.3                      | externaltweaker-1.12-0.3.jar                       | None                                     |
	| LCH   | geckolib3                         | 3.0.0                    | forge-1.12.2-geckolib-3.0.0-beta.7.1.jar           | None                                     |
	| LCH   | forgelin                          | 1.8.4                    | Forgelin-1.8.4.jar                                 | None                                     |
	| LCH   | forgemultipartcbe                 | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | microblockcbe                     | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | None                                     |
	| LCH   | minecraftmultipartcbe             | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | None                                     |
	| LCH   | geneticsreborn                    | 1.28                     | geneticsreborn-1.12-1.32.jar                       | None                                     |
	| LCH   | grapplemod                        | 1.12.2-v11.1             | grapplemod-v11.1-1.12.2.jar                        | None                                     |
	| LCH   | gravisuite                        | 3.1.1                    | Gravitation Suite-3.1.1.jar                        | None                                     |
	| LCH   | gravisuitepatch                   | 1.0.0                    | GraviSuite-Patcher-1.0.0.jar                       | None                                     |
	| LCH   | waila                             | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LCH   | ic2cropplugin                     | 1.1                      | IC2CropBreeding Plugin V1.12-1.1.jar               | None                                     |
	| LCH   | mekanism                          | 1.12.2-9.8.3.390         | Mekanism-1.12.2-9.8.3.390.jar                      | None                                     |
	| LCH   | teslacorelib                      | 1.0.17                   | tesla-core-lib-1.12.2-1.0.17.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | industrialforegoing               | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.12.13-237.jar         | None                                     |
	| LCH   | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCH   | ironchest                         | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
	| LCH   | journeymap                        | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                        | None                                     |
	| LCH   | jeid                              | 1.0.3-55                 | JustEnoughIDs-1.0.3-55.jar                         | None                                     |
	| LCH   | lm                                | 2.0.1                    | lm-2.0.1.jar                                       | None                                     |
	| LCH   | lovely_robot                      | 1.1.0                    | lovely_robot-1.12.2-1.1.0.jar                      | None                                     |
	| LCH   | mcjtylib_ng                       | 3.5.4                    | mcjtylib-1.12-3.5.4.jar                            | None                                     |
	| LCH   | morebees                          | 1.12.2-2.0.1             | morebees-1.12.2-2.0.1.jar                          | None                                     |
	| LCH   | mrtjpcore                         | 2.1.4.43                 | MrTJPCore-1.12.2-2.1.4.43-universal.jar            | None                                     |
	| LCH   | notenoughpets                     | 2.3.0                    | NotEnoughPets-1.12.2-2.3.0.jar                     | None                                     |
	| LCH   | examplemod                        | 1.0                      | NuclearCraft-2.18z-1.12.2.jar                      | None                                     |
	| LCH   | nuclearcraft                      | 2.18z                    | NuclearCraft-2.18z-1.12.2.jar                      | None                                     |
	| LCH   | dimensionalores                   | 1.0.5                    | Pomarf's+Dimensional+Ores+[1.12.2]+(v1.0.5).jar    | None                                     |
	| LCH   | projectred-core                   | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-Base.jar               | None                                     |
	| LCH   | redstonepaste                     | 1.7.5                    | redstonepaste-mc1.12-1.7.5.jar                     | None                                     |
	| LCH   | rftools                           | 7.73                     | rftools-1.12-7.73.jar                              | None                                     |
	| LCH   | sereneseasons                     | 1.2.18                   | SereneSeasons-1.12.2-1.2.18-universal.jar          | None                                     |
	| LCE   | sexmod                            | 1.0                      | sexmod-1.0-new.jar                                 | None                                     |
	| LC    | techguns                          | 2.0.2.0                  | techguns-1.12.2-2.0.2.0_pre3.2.jar                 | None                                     |
	| LC    | technicallights                   | 1.0.1.2                  | technicallights-1.0.1.2.jar                        | None                                     |
	| LC    | thermaldynamics                   | 2.5.6                    | ThermalDynamics-1.12.2-2.5.6.1-universal.jar       | None                                     |
	| LC    | thermalinnovation                 | 0.3.6                    | ThermalInnovation-1.12.2-0.3.6.1-universal.jar     | None                                     |
	| LC    | unclegglass                       | 1.12.2-2.0.0             | unclegglass-1.12.2-2.0.0.jar                       | None                                     |
	| LC    | discordrpc                        | 1.3.3                    | discordrpc-1.3.3-1.12.jar                          | None                                     |
	| LC    | teslacorelib_registries           | 1.0.17                   | tesla-core-lib-1.12.2-1.0.17.jar                   | None                                     |

	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore_v1.10.61_mc1.12.2.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
CorePlugin (SmoothFont-mc1.12.2-2.1.2.jar)
  bre.smoothfont.asm.Transformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  li.cil.oc.common.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-55.jar)
  org.dimdev.jeid.JEIDTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
  techguns.core.TechgunsASMTransformer
PatcherPlugin (GraviSuite-Patcher-1.0.0.jar)
  mods.su5ed.gravisuitepatch.asm.ClassTransformer
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Ender IO: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'Magma'
	Type: Dedicated Server (map_server.txt)
```

**Comment by anthony1x6000** [comment]
Had the same issue. The mod isn't yet compatible with forge servers and only works on LAN servers. 
The creator of the mod tweeted on July 30th that they'll [start to work on the mod again](https://twitter.com/Schnurri_tv/status/1421067098151866376), so hopefully, multiplayer support will come soon.
